--
-- Query contributed by 齐勤 (QI Qin)
--
--sorry i have not complete this lab before the DDL... 
--if i finish it ,then i will send it to your email..... 
--at last, giving my early wish: merry christmas.....